import placeholder from "../public/placeholder.svg";

export const tableDemoData = [
  {
    id: 1,
    image: placeholder,
    name: "Laser Lemonade Machine",
    status: "Draft",
    price: "$499.99",
    totalSales: 25,
    createdAt: "2023-07-12 10:42 AM",
  },
  {
    id: 2,
    image: placeholder,
    name: "Hypernova Headphones",
    status: "Active",
    price: "$129.99",
    totalSales: 100,
    createdAt: "2023-10-18 03:21 PM",
  },
  {
    id: 3,
    image: placeholder,
    name: "AeroGlow Desk Lamp",
    status: "Active",
    price: "$39.99",
    totalSales: 50,
    createdAt: "2023-11-29 08:15 AM",
  },
  {
    id: 4,
    image: placeholder,
    name: "TechTonic Energy Drink",
    status: "Draft",
    price: "$2.99",
    totalSales: 0,
    createdAt: "2023-12-25 11:59 PM",
  },
  {
    id: 5,
    image: placeholder,
    name: "Gamer Gear Pro Controller",
    status: "Active",
    price: "$59.99",
    totalSales: 75,
    createdAt: "2024-01-01 12:00 AM",
  },
  {
    id: 6,
    image: placeholder,
    name: "Luminous VR Headset",
    status: "Active",
    price: "$199.99",
    totalSales: 30,
    createdAt: "2024-02-14 02:14 PM",
  },
];
